[Log]
Level="warn"
 
[WebServer]
AllowOrigins="*"
SecureCookies=false

[WebServer.TLS]
HTTPSPort=0

[[EVM]]
ChainID=<CHAIN_ID>
Enabled=true
FinalityDepth=5
MinContractPayment="0"

[EVM.GasEstimator]
Mode = "FeeHistory"
TipCapDefault = "<TIP_CAP_DEFAULT>"
TipCapMin     = "30000000"       # 0.03 gwei
FeeCapDefault = "<FEE_CAP_DEFAULT>"
# EstimateLimit = true

[EVM.HeadTracker]
SamplingInterval = "30s"            # coalesce heads
HistoryDepth = 25

[EVM.NodePool]
PollInterval   = "80s"
NewHeadsPollInterval = "30s"
SyncThreshold = 10

 
[EVM.Transactions]
ReaperInterval = "30m"              # Less frequent cleanup
ReaperThreshold = "168h"            # Keep txns longer before cleanup
MaxInFlight = 32
MaxQueued = 64

[[EVM.Nodes]]
Name="<NETWORK_NAME>"
WSURL="<WS_URL>"
HTTPURL="<HTTP_URL>"
