site_name: Verdikta Arbiter Node Installation Guide
site_description: Complete guide for installing and managing Verdikta Arbiter Nodes
site_author: Verdikta Team
site_url: https://docs.verdikta.com

# Docs directory (set to current directory since structure was flattened)
docs_dir: .

# Repository
repo_name: verdikta-arbiter
repo_url: https://github.com/verdikta/verdikta-arbiter
edit_uri: edit/main/installer/docs/

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/verdikta
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/verdikta

# Custom CSS
extra_css:
  - assets/stylesheets/verdikta.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: verdikta
      repo: verdikta-arbiter
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - overview.md
    - Prerequisites: prerequisites.md
    - Quick Start: quick-start.md
  - Installation:
    - installation/index.md
    - Prompts Guide: installation/prompts-guide.md
    - Automated Installation: installation/automated.md
    - Manual Installation: installation/manual.md
    - Environment Setup: installation/environment.md
    - Component Installation:
      - AI Node: installation/components/ai-node.md
      - External Adapter: installation/components/external-adapter.md
      - Docker & PostgreSQL: installation/components/docker-postgres.md
      - Chainlink Node: installation/components/chainlink.md
      - Smart Contracts: installation/components/smart-contracts.md
      - Configuration: installation/components/configuration.md
  - Management:
    - management/index.md
    - Starting Services: management/starting.md
    - Stopping Services: management/stopping.md
    - Status Monitoring: management/status.md
    - Logs & Debugging: management/logs.md
  - Oracle Registration:
    - oracle/index.md
    - Dispatcher Registration: oracle/dispatcher.md
    - Contract Queries: oracle/queries.md
    - Verification: oracle/verification.md
  - Maintenance:
    - maintenance/index.md
    - Upgrading: maintenance/upgrading.md
    - Backup & Restore: maintenance/backup.md
    - Configuration Files: maintenance/configuration.md
  - Troubleshooting:
    - troubleshooting/index.md
    - Common Issues: troubleshooting/common-issues.md
    - Log Analysis: troubleshooting/logs.md
    - Support: troubleshooting/support.md
  - Reference:
    - reference/index.md
    - Script Reference: reference/scripts.md
    - Configuration Reference: reference/configuration.md
    - API Endpoints: reference/api.md
    - File Locations: reference/files.md 